require_relative './lib/hash_map'
map = HashMap.new
map.set('yellow', 'banana')
map.set('black', 'hat')
map.set('white', 'wall')
map.set('brown', 'face')
map.set('blue', 'jw sign')
map.set('red', "rabbi's outter garment")
map.set('yellowbone', 'peter Strikes')
map.set('lightbrown', 'samson')
map.set('peach', 'my skin')
map.set('cream', 'nivea')
map.set('gray', 'nokia')
map.set('navy', 'laptop')
map.set('gravy', 'ekse mama wam')
map.set('akkalo', 'hellow world')
map.set('kakama', 'mafohlo')
map.set('rashford', 'man united')
map.set('Eriskson', 'babamu')
map.set('dumbynigga', 'fafamu')
map.set('kopano', 'police station')
map.set('Turflaagte', 'jw congregation')
map.set("phase 3", 'Tshimo')
map.set('st', 'fishman')
map.set('ka', "foofoo")
p "#{map.collisions} collisions"